### ISSUE TITLE
Decouple from externals

### ISSUE THREAD

**Issue by SwooshyCueb** [jasoncoposky/mungefs#31]
This project, like irods, is very much built atop irods-externals. However, unlike irods, there's not much standing in the way of decoupling from externals today. For example, since we already have a workflow for pre-build configuration with arguments (see externals repo), there is no need to provide the capability of a default configuration using irods-externals.

For this project, this will be a pretty huge step towards normal and boring packaging, and will serve as a preview of some of the buildsystem changes eventually coming for the irods project.

**Comment by trel** [comment]
i like it.

**Comment by alanking** [comment]
Maybe related to and/or closes and/or invalidates #10?

**Comment by SwooshyCueb** [comment]
> Maybe related to and/or closes and/or invalidates #10?

Sure does! Nice catch
